# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'threading_details.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(669, 594)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(50, 30, 581, 81))
        self.groupBox.setObjectName("groupBox")
        self.threadLocation = QtWidgets.QWidget(self.groupBox)
        self.threadLocation.setGeometry(QtCore.QRect(15, 25, 250, 56))
        self.threadLocation.setMaximumSize(QtCore.QSize(250, 16777215))
        self.threadLocation.setStyleSheet("min-height: 30px;")
        self.threadLocation.setObjectName("threadLocation")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.threadLocation)
        self.horizontalLayout_40.setContentsMargins(0, 0, 0, 10)
        self.horizontalLayout_40.setSpacing(0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.btnExternal_2 = QtWidgets.QPushButton(self.threadLocation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.btnExternal_2.sizePolicy().hasHeightForWidth())
        self.btnExternal_2.setSizePolicy(sizePolicy)
        self.btnExternal_2.setMinimumSize(QtCore.QSize(0, 42))
        self.btnExternal_2.setMaximumSize(QtCore.QSize(16777215, 42))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.btnExternal_2.setFont(font)
        self.btnExternal_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnExternal_2.setStyleSheet("QPushButton {\n"
"    max-height: 30px;\n"
"    margin-top: 2px;\n"
"    margin-bottom: 2px;\n"
"    color: white;\n"
"    background:  qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                     stop: 0 #4e4e4e, stop: 1.0 #3a3a3a);\n"
"    border-style: solid;\n"
"    border-color: black;\n"
"    border-top-width: 2px;\n"
"    border-bottom-width: 2px;\n"
"    border-right-width: 1px;\n"
"    border-left-width: 2px;\n"
"    padding: 2px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:hover {\n"
"    background:  qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                     stop: 0 #A19E9E, stop: 1.0 #5C5959);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background:  qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(112, 112, 238, 255), stop:0.121053 rgba(123, 123, 232, 255), stop:0.3 rgba(85, 85, 238, 255), stop:0.694737 rgba(85, 85, 238, 255), stop:0.915789 rgba(123, 123, 232, 255), stop:1 rgba(112, 112, 238, 255))\n"
"}")
        self.btnExternal_2.setCheckable(True)
        self.btnExternal_2.setChecked(True)
        self.btnExternal_2.setAutoExclusive(True)
        self.btnExternal_2.setProperty("page", 0)
        self.btnExternal_2.setObjectName("btnExternal_2")
        self.horizontalLayout_40.addWidget(self.btnExternal_2)
        self.btnInternal_2 = QtWidgets.QPushButton(self.threadLocation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.btnInternal_2.sizePolicy().hasHeightForWidth())
        self.btnInternal_2.setSizePolicy(sizePolicy)
        self.btnInternal_2.setMinimumSize(QtCore.QSize(0, 42))
        self.btnInternal_2.setMaximumSize(QtCore.QSize(16777215, 42))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.btnInternal_2.setFont(font)
        self.btnInternal_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnInternal_2.setStyleSheet("QPushButton {\n"
"    max-height: 30px;\n"
"    margin-top: 2px;\n"
"    margin-bottom: 2px;\n"
"    color: white;\n"
"    background:  qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                     stop: 0 #4e4e4e, stop: 1.0 #3a3a3a);\n"
"    border-style: solid;\n"
"    border-color: black;\n"
"    border-top-width: 2px;\n"
"    border-bottom-width: 2px;\n"
"    border-right-width: 1px;\n"
"    border-left-width: 2px;\n"
"    padding: 2px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:hover {\n"
"    background:  qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                     stop: 0 #A19E9E, stop: 1.0 #5C5959);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background:  qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(112, 112, 238, 255), stop:0.121053 rgba(123, 123, 232, 255), stop:0.3 rgba(85, 85, 238, 255), stop:0.694737 rgba(85, 85, 238, 255), stop:0.915789 rgba(123, 123, 232, 255), stop:1 rgba(112, 112, 238, 255))\n"
"}")
        self.btnInternal_2.setCheckable(True)
        self.btnInternal_2.setAutoExclusive(True)
        self.btnInternal_2.setProperty("page", 2)
        self.btnInternal_2.setObjectName("btnInternal_2")
        self.horizontalLayout_40.addWidget(self.btnInternal_2)
        self.label_65 = QtWidgets.QLabel(Form)
        self.label_65.setGeometry(QtCore.QRect(45, 135, 51, 30))
        self.label_65.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.label_65.setObjectName("label_65")
        self.label_70 = QtWidgets.QLabel(Form)
        self.label_70.setGeometry(QtCore.QRect(155, 135, 29, 30))
        self.label_70.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.label_70.setObjectName("label_70")
        self.threadingPitch = VCPSettingsLineEdit(Form)
        self.threadingPitch.setGeometry(QtCore.QRect(95, 135, 56, 30))
        self.threadingPitch.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.threadingPitch.setAlignment(QtCore.Qt.AlignCenter)
        self.threadingPitch.setProperty("textFormat", "")
        self.threadingPitch.setObjectName("threadingPitch")
        self.threadingStarts = VCPSettingsComboBox(Form)
        self.threadingStarts.setGeometry(QtCore.QRect(295, 135, 51, 30))
        self.threadingStarts.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.threadingStarts.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.threadingStarts.setObjectName("threadingStarts")
        self.label_68 = QtWidgets.QLabel(Form)
        self.label_68.setGeometry(QtCore.QRect(240, 135, 51, 30))
        self.label_68.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.label_68.setObjectName("label_68")
        self.threadLabelXEnd = QtWidgets.QLabel(Form)
        self.threadLabelXEnd.setGeometry(QtCore.QRect(45, 240, 101, 30))
        self.threadLabelXEnd.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.threadLabelXEnd.setObjectName("threadLabelXEnd")
        self.threadingXStart = TeachInLineEdit(Form)
        self.threadingXStart.setGeometry(QtCore.QRect(150, 190, 76, 30))
        self.threadingXStart.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.threadingXStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.threadingXStart.setProperty("referenceType", 1)
        self.threadingXStart.setProperty("axisNumber", 0)
        self.threadingXStart.setProperty("latheMode", 2)
        self.threadingXStart.setObjectName("threadingXStart")
        self.threadingTeachXBtn = QtWidgets.QPushButton(Form)
        self.threadingTeachXBtn.setGeometry(QtCore.QRect(235, 190, 80, 31))
        self.threadingTeachXBtn.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.threadingTeachXBtn.setObjectName("threadingTeachXBtn")
        self.threadingCompute = QtWidgets.QPushButton(Form)
        self.threadingCompute.setGeometry(QtCore.QRect(235, 240, 80, 31))
        self.threadingCompute.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.threadingCompute.setObjectName("threadingCompute")
        self.threadLabelXStart = QtWidgets.QLabel(Form)
        self.threadLabelXStart.setGeometry(QtCore.QRect(45, 190, 101, 30))
        self.threadLabelXStart.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.threadLabelXStart.setObjectName("threadLabelXStart")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(145, 280, 176, 66))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.threadingTeachZBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.threadingTeachZBtn.setGeometry(QtCore.QRect(90, 30, 80, 31))
        self.threadingTeachZBtn.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.threadingTeachZBtn.setObjectName("threadingTeachZBtn")
        self.threadingZEnd = TeachInLineEdit(self.groupBox_2)
        self.threadingZEnd.setGeometry(QtCore.QRect(5, 30, 76, 30))
        self.threadingZEnd.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.threadingZEnd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.threadingZEnd.setProperty("referenceType", 1)
        self.threadingZEnd.setProperty("axisNumber", 2)
        self.threadingZEnd.setProperty("latheMode", 0)
        self.threadingZEnd.setObjectName("threadingZEnd")
        self.threadingXEnd = QtWidgets.QLineEdit(Form)
        self.threadingXEnd.setGeometry(QtCore.QRect(150, 240, 76, 30))
        self.threadingXEnd.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.threadingXEnd.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.threadingXEnd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.threadingXEnd.setObjectName("threadingXEnd")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(425, 130, 81, 30))
        self.label_21.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.label_21.setObjectName("label_21")
        self.label_73 = QtWidgets.QLabel(Form)
        self.label_73.setGeometry(QtCore.QRect(595, 130, 51, 30))
        self.label_73.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.label_73.setObjectName("label_73")
        self.label_69 = QtWidgets.QLabel(Form)
        self.label_69.setGeometry(QtCore.QRect(390, 300, 136, 30))
        self.label_69.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.label_69.setObjectName("label_69")
        self.label_72 = QtWidgets.QLabel(Form)
        self.label_72.setGeometry(QtCore.QRect(390, 190, 136, 30))
        self.label_72.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.label_72.setObjectName("label_72")
        self.threadingFirstPass = VCPSettingsLineEdit(Form)
        self.threadingFirstPass.setGeometry(QtCore.QRect(530, 130, 56, 30))
        self.threadingFirstPass.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.threadingFirstPass.setAlignment(QtCore.Qt.AlignCenter)
        self.threadingFirstPass.setProperty("textFormat", "")
        self.threadingFirstPass.setObjectName("threadingFirstPass")
        self.label_71 = QtWidgets.QLabel(Form)
        self.label_71.setGeometry(QtCore.QRect(390, 245, 101, 30))
        self.label_71.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.label_71.setObjectName("label_71")
        self.threadingTaper = VCPSettingsComboBox(Form)
        self.threadingTaper.setGeometry(QtCore.QRect(495, 245, 91, 31))
        self.threadingTaper.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.threadingTaper.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.threadingTaper.setObjectName("threadingTaper")
        self.threadingDepthDegression = VCPSettingsComboBox(Form)
        self.threadingDepthDegression.setGeometry(QtCore.QRect(535, 190, 51, 31))
        self.threadingDepthDegression.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.threadingDepthDegression.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.threadingDepthDegression.setObjectName("threadingDepthDegression")
        self.threadingSpringPasses = VCPSettingsComboBox(Form)
        self.threadingSpringPasses.setGeometry(QtCore.QRect(535, 355, 51, 31))
        self.threadingSpringPasses.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.threadingSpringPasses.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.threadingSpringPasses.setObjectName("threadingSpringPasses")
        self.threadingCompAngle = VCPSettingsLineEdit(Form)
        self.threadingCompAngle.setGeometry(QtCore.QRect(530, 300, 56, 30))
        self.threadingCompAngle.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.threadingCompAngle.setAlignment(QtCore.Qt.AlignCenter)
        self.threadingCompAngle.setProperty("textFormat", "")
        self.threadingCompAngle.setObjectName("threadingCompAngle")
        self.label_66 = QtWidgets.QLabel(Form)
        self.label_66.setGeometry(QtCore.QRect(390, 355, 106, 30))
        self.label_66.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.label_66.setObjectName("label_66")
        self.validateAndSave = QtWidgets.QPushButton(Form)
        self.validateAndSave.setGeometry(QtCore.QRect(270, 495, 186, 46))
        self.validateAndSave.setObjectName("validateAndSave")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Thread Location"))
        self.btnExternal_2.setText(_translate("Form", "External"))
        self.btnInternal_2.setText(_translate("Form", "Internal"))
        self.label_65.setText(_translate("Form", "Pitch:"))
        self.label_70.setText(_translate("Form", "mm"))
        self.threadingPitch.setText(_translate("Form", "0.1"))
        self.threadingPitch.setProperty("settingName", _translate("Form", "smart_numpad.quick-cycles-thread-pitch-metric"))
        self.threadingStarts.setProperty("settingName", _translate("Form", "quick-cycles.threading-starts"))
        self.label_68.setText(_translate("Form", "Starts:"))
        self.threadLabelXEnd.setText(_translate("Form", "Minor Diam."))
        self.threadingXStart.setProperty("inchFormat", _translate("Form", "%9.4f"))
        self.threadingXStart.setProperty("millimeterFormat", _translate("Form", "%10.3f"))
        self.threadingXStart.setProperty("degreeFormat", _translate("Form", "%10.2f"))
        self.threadingTeachXBtn.setText(_translate("Form", "TeachIn X"))
        self.threadingCompute.setText(_translate("Form", "Compute"))
        self.threadLabelXStart.setText(_translate("Form", "Major Diam."))
        self.groupBox_2.setTitle(_translate("Form", "Z End"))
        self.threadingTeachZBtn.setText(_translate("Form", "TeachIn Z"))
        self.threadingZEnd.setProperty("inchFormat", _translate("Form", "%9.4f"))
        self.threadingZEnd.setProperty("millimeterFormat", _translate("Form", "%10.3f"))
        self.threadingZEnd.setProperty("degreeFormat", _translate("Form", "%10.2f"))
        self.label_21.setText(_translate("Form", "First pass:"))
        self.label_73.setText(_translate("Form", "mm/⌀"))
        self.label_69.setText(_translate("Form", "Compound angle:"))
        self.label_72.setText(_translate("Form", "Depth degression:"))
        self.threadingFirstPass.setText(_translate("Form", "0.1"))
        self.threadingFirstPass.setProperty("settingName", _translate("Form", "smart_numpad.quick-cycles-thread-first-pass"))
        self.label_71.setText(_translate("Form", "Thread taper :"))
        self.threadingTaper.setProperty("settingName", _translate("Form", "quick-cycles.threading-taper"))
        self.threadingDepthDegression.setProperty("settingName", _translate("Form", "quick-cycles.threading-depth-degression"))
        self.threadingSpringPasses.setProperty("settingName", _translate("Form", "quick-cycles.threading-spring-passes"))
        self.threadingCompAngle.setText(_translate("Form", "30"))
        self.threadingCompAngle.setProperty("settingName", _translate("Form", "smart_numpad.quick-cycles-threading-compound-angle"))
        self.label_66.setText(_translate("Form", "Spring passes:"))
        self.validateAndSave.setText(_translate("Form", "Validate && Save"))
from qtpyvcp.widgets.input_widgets.setting_slider import VCPSettingsComboBox, VCPSettingsLineEdit
from qtpyvcp.widgets.input_widgets.teachin_line_edit import TeachInLineEdit
