import json
import os
from datetime import datetime

from .operations import OPERATION_GENERATORS
from teachinlathe.conversational.data_types import display_names


def _safe_program_name(program_dict):
    header = program_dict.get("header", {}) if isinstance(program_dict, dict) else {}
    name = header.get("name", program_dict.get("id", "program"))
    safe = "".join(c for c in str(name) if c.isalnum() or c in ("-", "_", " ")).strip()
    return safe.replace(" ", "_")


def build_ngc_from_json(json_path, output_dir=None):
    if not json_path or not os.path.isfile(json_path):
        raise FileNotFoundError(f"Program JSON not found: {json_path}")

    with open(json_path, "r", encoding="utf-8") as handle:
        program_dict = json.load(handle)

    base_no_ext, _ = os.path.splitext(json_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
        ngc_path = os.path.join(output_dir, os.path.basename(base_no_ext) + ".ngc")
    else:
        ngc_path = base_no_ext + ".ngc"

    lines = []
    program_name = program_dict.get("header", {}).get("name", program_dict.get("id", "program"))
    lines.append("( Generated by ConversationalQml gcode_builder )")
    lines.append(f"( Program: {program_name} )")
    lines.append(f"( Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} )")
    lines.append("G21  (mm)")
    lines.append("G90  (absolute)")
    lines.append("G94  (feed per min)")
    lines.append("G18  (ZX plane)")
    lines.append("")

    datum = int(program_dict.get("header", {}).get("datum", 1))
    operations = program_dict.get("operations", [])
    for index, op in enumerate(operations, 1):
        op = dict(op)
        op["_datum"] = datum
        op_type = op.get("type", "unknown")
        if not bool(op.get("generate_gcode", True)):
            continue

        op_display = display_names.get(op_type, op_type)
        lines.append(f"(----------Operation #{index}: {op_display}----------)\n")

        if op_type == "customProfiling":
            profile_id = int((op.get("profiling_parameters") or {}).get("profile_id", 0))
            profile_op = next(
                (o for o in operations
                 if o.get("type") == "defineProfile" and int(o.get("profile_id", -1)) == profile_id),
                {}
            )
            op["_resolved_profile"] = profile_op

        generator = OPERATION_GENERATORS.get(op_type)
        if generator:
            lines.extend(generator(op))
        else:
            lines.append(f"( TODO: gcode generator for type={op_type} )")
        lines.append("")
    lines.append("")
    lines.append("M30")

    with open(ngc_path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))

    return ngc_path
