# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lathe_fixture.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(191, 286)
        Form.setStyleSheet("")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 191, 286))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 230, 81, 21))
        self.label_6.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(10, 255, 61, 21))
        self.label_9.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.label_9.setObjectName("label_9")
        self.description = QtWidgets.QLabel(self.frame)
        self.description.setGeometry(QtCore.QRect(10, 155, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.description.setFont(font)
        self.description.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.description.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.description.setAlignment(QtCore.Qt.AlignCenter)
        self.description.setWordWrap(True)
        self.description.setObjectName("description")
        self.zMinusLimit = QtWidgets.QLabel(self.frame)
        self.zMinusLimit.setGeometry(QtCore.QRect(75, 255, 61, 21))
        self.zMinusLimit.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.zMinusLimit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zMinusLimit.setObjectName("zMinusLimit")
        self.imageView = QtWidgets.QLabel(self.frame)
        self.imageView.setGeometry(QtCore.QRect(20, 5, 150, 150))
        self.imageView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageView.setAlignment(QtCore.Qt.AlignCenter)
        self.imageView.setObjectName("imageView")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 205, 81, 21))
        self.label_2.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.label_2.setObjectName("label_2")
        self.maxRpm = QtWidgets.QLabel(self.frame)
        self.maxRpm.setGeometry(QtCore.QRect(90, 230, 46, 21))
        self.maxRpm.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.maxRpm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxRpm.setObjectName("maxRpm")
        self.units = QtWidgets.QLabel(self.frame)
        self.units.setGeometry(QtCore.QRect(140, 205, 36, 21))
        self.units.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.units.setAlignment(QtCore.Qt.AlignCenter)
        self.units.setObjectName("units")
        self.diameter = QtWidgets.QLabel(self.frame)
        self.diameter.setGeometry(QtCore.QRect(100, 205, 36, 21))
        self.diameter.setStyleSheet("font: 11pt \"Noto Sans\";")
        self.diameter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.diameter.setObjectName("diameter")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "Max RPM:"))
        self.label_9.setText(_translate("Form", "Z- Limit:"))
        self.description.setText(_translate("Form", "Rohm 3 Jaws chuck with a long long text"))
        self.zMinusLimit.setText(_translate("Form", "000.000"))
        self.imageView.setText(_translate("Form", "No Image"))
        self.label_2.setText(_translate("Form", "Diameter:"))
        self.maxRpm.setText(_translate("Form", "2000"))
        self.units.setText(_translate("Form", "mm"))
        self.diameter.setText(_translate("Form", "000"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
