# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cnc/Work/teachinlathe/src/teachinlathe/widgets/conversational/program_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(959, 60)
        self.btnEdit = QtWidgets.QPushButton(Form)
        self.btnEdit.setGeometry(QtCore.QRect(690, 10, 106, 41))
        self.btnEdit.setObjectName("btnEdit")
        self.btnDelete = QtWidgets.QPushButton(Form)
        self.btnDelete.setGeometry(QtCore.QRect(840, 10, 86, 41))
        self.btnDelete.setObjectName("btnDelete")
        self.labelLastEdited = QtWidgets.QLabel(Form)
        self.labelLastEdited.setGeometry(QtCore.QRect(400, 15, 166, 29))
        self.labelLastEdited.setObjectName("labelLastEdited")
        self.labelName = QtWidgets.QLabel(Form)
        self.labelName.setGeometry(QtCore.QRect(20, 15, 291, 29))
        self.labelName.setObjectName("labelName")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnEdit.setText(_translate("Form", "Edit"))
        self.btnDelete.setText(_translate("Form", "Delete"))
        self.labelLastEdited.setText(_translate("Form", "LastEdited"))
        self.labelName.setText(_translate("Form", "ProgramName"))
