# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_edit_tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(683, 932)
        self.saveButton = QtWidgets.QPushButton(Form)
        self.saveButton.setGeometry(QtCore.QRect(565, 880, 106, 40))
        self.saveButton.setObjectName("saveButton")
        self.cancelButton = QtWidgets.QPushButton(Form)
        self.cancelButton.setGeometry(QtCore.QRect(10, 880, 111, 40))
        self.cancelButton.setObjectName("cancelButton")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(10, 95, 111, 36))
        self.label_16.setStyleSheet("font: 13pt \"Cantarell\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(10, 150, 111, 36))
        self.label_17.setStyleSheet("font: 13pt \"Cantarell\";")
        self.label_17.setObjectName("label_17")
        self.actualFeedType_3 = QtWidgets.QLabel(Form)
        self.actualFeedType_3.setGeometry(QtCore.QRect(225, 150, 36, 36))
        self.actualFeedType_3.setStyleSheet("font: 13pt \"Cantarell\";")
        self.actualFeedType_3.setObjectName("actualFeedType_3")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(5, 310, 261, 276))
        self.groupBox_2.setStyleSheet("font: 13pt \"Cantarell\";")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.orientationGrid = QtWidgets.QWidget(self.groupBox_2)
        self.orientationGrid.setGeometry(QtCore.QRect(5, 25, 250, 250))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orientationGrid.sizePolicy().hasHeightForWidth())
        self.orientationGrid.setSizePolicy(sizePolicy)
        self.orientationGrid.setObjectName("orientationGrid")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.orientationGrid)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.orient5 = QtWidgets.QPushButton(self.orientationGrid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orient5.sizePolicy().hasHeightForWidth())
        self.orient5.setSizePolicy(sizePolicy)
        self.orient5.setMinimumSize(QtCore.QSize(70, 70))
        self.orient5.setMaximumSize(QtCore.QSize(70, 70))
        self.orient5.setStyleSheet("QPushButton:checked {\n"
"    background-color: #add8e6; \n"
"    border-radius: 4px;\n"
"}")
        self.orient5.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/lathe_control_point_5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.orient5.setIcon(icon)
        self.orient5.setIconSize(QtCore.QSize(65, 65))
        self.orient5.setCheckable(True)
        self.orient5.setAutoExclusive(True)
        self.orient5.setObjectName("orient5")
        self.orientButtonGroup = QtWidgets.QButtonGroup(Form)
        self.orientButtonGroup.setObjectName("orientButtonGroup")
        self.orientButtonGroup.addButton(self.orient5)
        self.gridLayout_2.addWidget(self.orient5, 1, 0, 1, 1)
        self.orient6 = QtWidgets.QPushButton(self.orientationGrid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orient6.sizePolicy().hasHeightForWidth())
        self.orient6.setSizePolicy(sizePolicy)
        self.orient6.setMinimumSize(QtCore.QSize(70, 70))
        self.orient6.setMaximumSize(QtCore.QSize(70, 70))
        self.orient6.setStyleSheet("QPushButton:checked {\n"
"    background-color: #add8e6; \n"
"    border-radius: 4px;\n"
"}")
        self.orient6.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/lathe_control_point_6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.orient6.setIcon(icon1)
        self.orient6.setIconSize(QtCore.QSize(65, 65))
        self.orient6.setCheckable(True)
        self.orient6.setAutoExclusive(True)
        self.orient6.setObjectName("orient6")
        self.orientButtonGroup.addButton(self.orient6)
        self.gridLayout_2.addWidget(self.orient6, 2, 1, 1, 1)
        self.orient3 = QtWidgets.QPushButton(self.orientationGrid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orient3.sizePolicy().hasHeightForWidth())
        self.orient3.setSizePolicy(sizePolicy)
        self.orient3.setMinimumSize(QtCore.QSize(70, 70))
        self.orient3.setMaximumSize(QtCore.QSize(70, 70))
        self.orient3.setStyleSheet("QPushButton:checked {\n"
"    background-color: #add8e6; \n"
"    border-radius: 4px;\n"
"}")
        self.orient3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/lathe_control_point_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.orient3.setIcon(icon2)
        self.orient3.setIconSize(QtCore.QSize(65, 65))
        self.orient3.setCheckable(True)
        self.orient3.setAutoExclusive(True)
        self.orient3.setObjectName("orient3")
        self.orientButtonGroup.addButton(self.orient3)
        self.gridLayout_2.addWidget(self.orient3, 0, 2, 1, 1)
        self.orient1 = QtWidgets.QPushButton(self.orientationGrid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orient1.sizePolicy().hasHeightForWidth())
        self.orient1.setSizePolicy(sizePolicy)
        self.orient1.setMinimumSize(QtCore.QSize(70, 70))
        self.orient1.setMaximumSize(QtCore.QSize(70, 70))
        self.orient1.setStyleSheet("QPushButton:checked {\n"
"    background-color: #add8e6; \n"
"    border-radius: 4px;\n"
"}")
        self.orient1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/lathe_control_point_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.orient1.setIcon(icon3)
        self.orient1.setIconSize(QtCore.QSize(65, 65))
        self.orient1.setCheckable(True)
        self.orient1.setAutoExclusive(True)
        self.orient1.setObjectName("orient1")
        self.orientButtonGroup.addButton(self.orient1)
        self.gridLayout_2.addWidget(self.orient1, 2, 0, 1, 1)
        self.orient7 = QtWidgets.QPushButton(self.orientationGrid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orient7.sizePolicy().hasHeightForWidth())
        self.orient7.setSizePolicy(sizePolicy)
        self.orient7.setMinimumSize(QtCore.QSize(70, 70))
        self.orient7.setMaximumSize(QtCore.QSize(70, 70))
        self.orient7.setStyleSheet("QPushButton:checked {\n"
"    background-color: #add8e6; \n"
"    border-radius: 4px;\n"
"}")
        self.orient7.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/lathe_control_point_7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.orient7.setIcon(icon4)
        self.orient7.setIconSize(QtCore.QSize(65, 65))
        self.orient7.setCheckable(True)
        self.orient7.setAutoExclusive(True)
        self.orient7.setObjectName("orient7")
        self.orientButtonGroup.addButton(self.orient7)
        self.gridLayout_2.addWidget(self.orient7, 1, 2, 1, 1)
        self.orient9 = QtWidgets.QPushButton(self.orientationGrid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orient9.sizePolicy().hasHeightForWidth())
        self.orient9.setSizePolicy(sizePolicy)
        self.orient9.setMinimumSize(QtCore.QSize(70, 70))
        self.orient9.setMaximumSize(QtCore.QSize(70, 70))
        self.orient9.setStyleSheet("QPushButton:checked {\n"
"    background-color: #add8e6; \n"
"    border-radius: 4px;\n"
"}")
        self.orient9.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/lathe_control_point_9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.orient9.setIcon(icon5)
        self.orient9.setIconSize(QtCore.QSize(65, 65))
        self.orient9.setCheckable(True)
        self.orient9.setAutoExclusive(True)
        self.orient9.setObjectName("orient9")
        self.orientButtonGroup.addButton(self.orient9)
        self.gridLayout_2.addWidget(self.orient9, 1, 1, 1, 1)
        self.orient2 = QtWidgets.QPushButton(self.orientationGrid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orient2.sizePolicy().hasHeightForWidth())
        self.orient2.setSizePolicy(sizePolicy)
        self.orient2.setMinimumSize(QtCore.QSize(70, 70))
        self.orient2.setMaximumSize(QtCore.QSize(70, 70))
        self.orient2.setStyleSheet("QPushButton:checked {\n"
"    background-color: #add8e6; \n"
"    border-radius: 4px;\n"
"}")
        self.orient2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/lathe_control_point_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.orient2.setIcon(icon6)
        self.orient2.setIconSize(QtCore.QSize(65, 65))
        self.orient2.setCheckable(True)
        self.orient2.setAutoExclusive(True)
        self.orient2.setObjectName("orient2")
        self.orientButtonGroup.addButton(self.orient2)
        self.gridLayout_2.addWidget(self.orient2, 2, 2, 1, 1)
        self.orient4 = QtWidgets.QPushButton(self.orientationGrid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orient4.sizePolicy().hasHeightForWidth())
        self.orient4.setSizePolicy(sizePolicy)
        self.orient4.setMinimumSize(QtCore.QSize(70, 70))
        self.orient4.setMaximumSize(QtCore.QSize(70, 70))
        self.orient4.setStyleSheet("QPushButton:checked {\n"
"    background-color: #add8e6; \n"
"    border-radius: 4px;\n"
"}")
        self.orient4.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/lathe_control_point_4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.orient4.setIcon(icon7)
        self.orient4.setIconSize(QtCore.QSize(65, 65))
        self.orient4.setCheckable(True)
        self.orient4.setAutoExclusive(True)
        self.orient4.setObjectName("orient4")
        self.orientButtonGroup.addButton(self.orient4)
        self.gridLayout_2.addWidget(self.orient4, 0, 0, 1, 1)
        self.orient8 = QtWidgets.QPushButton(self.orientationGrid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orient8.sizePolicy().hasHeightForWidth())
        self.orient8.setSizePolicy(sizePolicy)
        self.orient8.setMinimumSize(QtCore.QSize(70, 70))
        self.orient8.setMaximumSize(QtCore.QSize(70, 70))
        self.orient8.setStyleSheet("QPushButton:checked {\n"
"    background-color: #add8e6; \n"
"    border-radius: 4px;\n"
"}")
        self.orient8.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/lathe_control_point_8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.orient8.setIcon(icon8)
        self.orient8.setIconSize(QtCore.QSize(65, 65))
        self.orient8.setCheckable(True)
        self.orient8.setAutoExclusive(True)
        self.orient8.setObjectName("orient8")
        self.orientButtonGroup.addButton(self.orient8)
        self.gridLayout_2.addWidget(self.orient8, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(10, 205, 111, 36))
        self.label_18.setStyleSheet("font: 13pt \"Cantarell\";")
        self.label_18.setObjectName("label_18")
        self.backAngleInput = QtWidgets.QLabel(Form)
        self.backAngleInput.setGeometry(QtCore.QRect(130, 205, 76, 36))
        self.backAngleInput.setStyleSheet("QLabel {\n"
"        border-style: solid;\n"
"        border-color: rgb(119, 118, 123);\n"
"        border-width: 1px;\n"
"        border-radius: 5px;\n"
"        color: rgb(154, 153, 150);\n"
"        background: rgb(246, 245, 244);\n"
"        font: 12pt \"Noto Sans Mono\";\n"
"}")
        self.backAngleInput.setAlignment(QtCore.Qt.AlignCenter)
        self.backAngleInput.setObjectName("backAngleInput")
        self.actualFeedType_4 = QtWidgets.QLabel(Form)
        self.actualFeedType_4.setGeometry(QtCore.QRect(220, 205, 36, 36))
        self.actualFeedType_4.setStyleSheet("font: 13pt \"Cantarell\";")
        self.actualFeedType_4.setObjectName("actualFeedType_4")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(10, 255, 111, 36))
        self.label_19.setStyleSheet("font: 13pt \"Cantarell\";")
        self.label_19.setObjectName("label_19")
        self.actualFeedType_5 = QtWidgets.QLabel(Form)
        self.actualFeedType_5.setGeometry(QtCore.QRect(220, 255, 36, 36))
        self.actualFeedType_5.setStyleSheet("font: 13pt \"Cantarell\";")
        self.actualFeedType_5.setObjectName("actualFeedType_5")
        self.frontAngleInput = QtWidgets.QLabel(Form)
        self.frontAngleInput.setGeometry(QtCore.QRect(130, 255, 76, 36))
        self.frontAngleInput.setStyleSheet("QLabel {\n"
"        border-style: solid;\n"
"        border-color: rgb(119, 118, 123);\n"
"        border-width: 1px;\n"
"        border-radius: 5px;\n"
"        color: rgb(154, 153, 150);\n"
"        background: rgb(246, 245, 244);\n"
"        font: 12pt \"Noto Sans Mono\";\n"
"}")
        self.frontAngleInput.setAlignment(QtCore.Qt.AlignCenter)
        self.frontAngleInput.setObjectName("frontAngleInput")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(10, 590, 111, 36))
        self.label_20.setStyleSheet("font: 13pt \"Cantarell\";")
        self.label_20.setObjectName("label_20")
        self.toolDescription = QtWidgets.QTextEdit(Form)
        self.toolDescription.setGeometry(QtCore.QRect(5, 630, 666, 141))
        self.toolDescription.setObjectName("toolDescription")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(5, 60, 676, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.titleLabel = QtWidgets.QLabel(Form)
        self.titleLabel.setGeometry(QtCore.QRect(250, 20, 191, 26))
        self.titleLabel.setStyleSheet("font: 16pt \"Cantarell\";")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(345, 90, 301, 331))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/lathe_tool_graphic.png"))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.toolNoInput = TouchFakeLineEdit(Form)
        self.toolNoInput.setGeometry(QtCore.QRect(145, 95, 61, 36))
        self.toolNoInput.setStyleSheet("QLabel {\n"
"        border-style: solid;\n"
"        border-color: rgb(119, 118, 123);\n"
"        border-width: 1px;\n"
"        border-radius: 5px;\n"
"        color: rgb(154, 153, 150);\n"
"        background: rgb(246, 245, 244);\n"
"        font: 12pt \"Noto Sans Mono\";\n"
"}")
        self.toolNoInput.setObjectName("toolNoInput")
        self.tipRadiusInput = TouchFakeLineEdit(Form)
        self.tipRadiusInput.setGeometry(QtCore.QRect(145, 150, 61, 36))
        self.tipRadiusInput.setStyleSheet("QLabel {\n"
"        border-style: solid;\n"
"        border-color: rgb(119, 118, 123);\n"
"        border-width: 1px;\n"
"        border-radius: 5px;\n"
"        color: rgb(154, 153, 150);\n"
"        background: rgb(246, 245, 244);\n"
"        font: 12pt \"Noto Sans Mono\";\n"
"}")
        self.tipRadiusInput.setObjectName("tipRadiusInput")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.saveButton.setText(_translate("Form", "Save"))
        self.cancelButton.setText(_translate("Form", "Cancel"))
        self.label_16.setText(_translate("Form", "Tool Number:"))
        self.label_17.setText(_translate("Form", "Tip Radius:"))
        self.actualFeedType_3.setText(_translate("Form", "mm"))
        self.groupBox_2.setTitle(_translate("Form", "Tip Orientatation"))
        self.label_18.setText(_translate("Form", "Back angle:"))
        self.backAngleInput.setText(_translate("Form", "0"))
        self.actualFeedType_4.setText(_translate("Form", "deg"))
        self.label_19.setText(_translate("Form", "Front angle:"))
        self.actualFeedType_5.setText(_translate("Form", "deg"))
        self.frontAngleInput.setText(_translate("Form", "0"))
        self.label_20.setText(_translate("Form", "Description:"))
        self.titleLabel.setText(_translate("Form", "Add new Tool"))
from qtpyvcp.widgets.input_widgets.touch_fake_line_edit import TouchFakeLineEdit
import teachinlathe_rc
