# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/vasimihalca/Work/teachinlathe/src/teachinlathe/widgets/teachin_lathe_dro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(817, 178)
        self.verticalFrame = QtWidgets.QFrame(Form)
        self.verticalFrame.setGeometry(QtCore.QRect(4, 4, 811, 171))
        self.verticalFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 10, -1)
        self.gridLayout.setHorizontalSpacing(11)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.zSecondaryDro = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zSecondaryDro.sizePolicy().hasHeightForWidth())
        self.zSecondaryDro.setSizePolicy(sizePolicy)
        self.zSecondaryDro.setMinimumSize(QtCore.QSize(150, 0))
        self.zSecondaryDro.setStyleSheet("font: 20pt \"Noto Sans\";")
        self.zSecondaryDro.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.zSecondaryDro.setObjectName("zSecondaryDro")
        self.gridLayout.addWidget(self.zSecondaryDro, 1, 0, 1, 1)
        self.xPrimaryDro = QtWidgets.QLabel(self.verticalFrame)
        self.xPrimaryDro.setStyleSheet("font: 50pt \"Noto Sans Display\";")
        self.xPrimaryDro.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xPrimaryDro.setObjectName("xPrimaryDro")
        self.gridLayout.addWidget(self.xPrimaryDro, 0, 2, 1, 1)
        self.zAbsRel = QtWidgets.QPushButton(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zAbsRel.sizePolicy().hasHeightForWidth())
        self.zAbsRel.setSizePolicy(sizePolicy)
        self.zAbsRel.setStyleSheet("QPushButton {\n"
"    min-height: 50px;\n"
"    min-width: 50px;\n"
"    font: 14pt \"DejaVu Sans\";\n"
"}")
        self.zAbsRel.setObjectName("zAbsRel")
        self.gridLayout.addWidget(self.zAbsRel, 1, 5, 1, 1)
        self.zZero = QtWidgets.QPushButton(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zZero.sizePolicy().hasHeightForWidth())
        self.zZero.setSizePolicy(sizePolicy)
        self.zZero.setStyleSheet("QPushButton {\n"
"    min-height: 50px;\n"
"    min-width: 50px;\n"
"    font: 14pt \"DejaVu Sans\";\n"
"}")
        self.zZero.setObjectName("zZero")
        self.gridLayout.addWidget(self.zZero, 1, 4, 1, 1)
        self.xZero = QtWidgets.QPushButton(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xZero.sizePolicy().hasHeightForWidth())
        self.xZero.setSizePolicy(sizePolicy)
        self.xZero.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.xZero.setStyleSheet("QPushButton {\n"
"    height: 50px;\n"
"    width: 50px;\n"
"    font: 14pt \"DejaVu Sans\";\n"
"}")
        self.xZero.setObjectName("xZero")
        self.gridLayout.addWidget(self.xZero, 0, 4, 1, 1)
        self.zLabel = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zLabel.sizePolicy().hasHeightForWidth())
        self.zLabel.setSizePolicy(sizePolicy)
        self.zLabel.setStyleSheet("font: 60pt \"Noto Sans\";")
        self.zLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.zLabel.setObjectName("zLabel")
        self.gridLayout.addWidget(self.zLabel, 1, 1, 1, 1)
        self.xSecondaryDro = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xSecondaryDro.sizePolicy().hasHeightForWidth())
        self.xSecondaryDro.setSizePolicy(sizePolicy)
        self.xSecondaryDro.setMinimumSize(QtCore.QSize(150, 0))
        self.xSecondaryDro.setStyleSheet("font: 20pt \"Noto Sans\";")
        self.xSecondaryDro.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.xSecondaryDro.setObjectName("xSecondaryDro")
        self.gridLayout.addWidget(self.xSecondaryDro, 0, 0, 1, 1)
        self.zPrimaryDro = QtWidgets.QLabel(self.verticalFrame)
        self.zPrimaryDro.setStyleSheet("font: 50pt \"Noto Sans Display\";")
        self.zPrimaryDro.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zPrimaryDro.setIndent(-1)
        self.zPrimaryDro.setObjectName("zPrimaryDro")
        self.gridLayout.addWidget(self.zPrimaryDro, 1, 2, 1, 1)
        self.xAbsRel = QtWidgets.QPushButton(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xAbsRel.sizePolicy().hasHeightForWidth())
        self.xAbsRel.setSizePolicy(sizePolicy)
        self.xAbsRel.setStyleSheet("QPushButton {\n"
"    min-height: 50px;\n"
"    min-width: 50px;\n"
"    font: 14pt \"DejaVu Sans\";\n"
"}")
        self.xAbsRel.setObjectName("xAbsRel")
        self.gridLayout.addWidget(self.xAbsRel, 0, 5, 1, 1)
        self.xUnit = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xUnit.sizePolicy().hasHeightForWidth())
        self.xUnit.setSizePolicy(sizePolicy)
        self.xUnit.setMinimumSize(QtCore.QSize(20, 0))
        self.xUnit.setStyleSheet("font: 20pt \"Noto Sans\";")
        self.xUnit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xUnit.setObjectName("xUnit")
        self.gridLayout.addWidget(self.xUnit, 0, 3, 1, 1)
        self.xLabel = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xLabel.sizePolicy().hasHeightForWidth())
        self.xLabel.setSizePolicy(sizePolicy)
        self.xLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.xLabel.setStyleSheet("font: 60pt \"Noto Sans\";")
        self.xLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.xLabel.setObjectName("xLabel")
        self.gridLayout.addWidget(self.xLabel, 0, 1, 1, 1)
        self.zUnit = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zUnit.sizePolicy().hasHeightForWidth())
        self.zUnit.setSizePolicy(sizePolicy)
        self.zUnit.setMinimumSize(QtCore.QSize(20, 0))
        self.zUnit.setStyleSheet("font: 20pt \"Noto Sans\";")
        self.zUnit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zUnit.setObjectName("zUnit")
        self.gridLayout.addWidget(self.zUnit, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.zSecondaryDro.setText(_translate("Form", "+0000.0000"))
        self.xPrimaryDro.setText(_translate("Form", "+0000.0000"))
        self.zAbsRel.setText(_translate("Form", "Abs/Rel"))
        self.zZero.setText(_translate("Form", "0"))
        self.xZero.setText(_translate("Form", "0"))
        self.zLabel.setText(_translate("Form", "Z"))
        self.xSecondaryDro.setText(_translate("Form", "+0000.0000"))
        self.zPrimaryDro.setText(_translate("Form", "+0000.0000"))
        self.xAbsRel.setText(_translate("Form", "Abs/Rel"))
        self.xUnit.setText(_translate("Form", "xx"))
        self.xLabel.setText(_translate("Form", "X"))
        self.zUnit.setText(_translate("Form", "zz"))
