# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/vasimihalca/Work/teachinlathe/src/teachinlathe/ui/widgets/teachin_lathe_dro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(769, 338)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 30, 631, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.manual_dro = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.manual_dro.setContentsMargins(0, 0, 0, 0)
        self.manual_dro.setObjectName("manual_dro")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("font: 60pt \"Noto Sans\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.drolabel = DROLabel(self.verticalLayoutWidget)
        self.drolabel.setStyleSheet("font: 75 50pt \"C059\";")
        self.drolabel.setProperty("referenceType", 1)
        self.drolabel.setProperty("axisNumber", 0)
        self.drolabel.setProperty("latheMode", 0)
        self.drolabel.setObjectName("drolabel")
        self.horizontalLayout.addWidget(self.drolabel)
        self.statuslabel = StatusLabel(self.verticalLayoutWidget)
        self.statuslabel.setStyleSheet("font: 30pt \"Noto Sans\";")
        self.statuslabel.setObjectName("statuslabel")
        self.horizontalLayout.addWidget(self.statuslabel)
        self.manual_dro.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.manual_dro.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "X"))
        self.drolabel.setProperty("inchFormat", _translate("Form", "%9.4f"))
        self.drolabel.setProperty("millimeterFormat", _translate("Form", "%10.3f"))
        self.drolabel.setProperty("degreeFormat", _translate("Form", "%10.2f"))
        self.statuslabel.setProperty("rules", _translate("Form", "[{\"name\": \"X Unit\", \"property\": \"Text\", \"expression\": \"\'mm\' if ch[0] else \'in\'\", \"channels\": [{\"url\": \"status:linear_units\", \"trigger\": true}]}]"))
from qtpyvcp.widgets.display_widgets.dro_label import DROLabel
from qtpyvcp.widgets.display_widgets.status_label import StatusLabel
