# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cnc/Work/teachinlathe/src/teachinlathe/widgets/teachin_lathe_dro.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1310, 703)
        self.zLabel = QtWidgets.QLabel(Form)
        self.zLabel.setGeometry(QtCore.QRect(5, 140, 60, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zLabel.sizePolicy().hasHeightForWidth())
        self.zLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans Narrow")
        font.setPointSize(60)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.zLabel.setFont(font)
        self.zLabel.setStyleSheet("font: 60pt \"Liberation Sans Narrow\";")
        self.zLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.zLabel.setObjectName("zLabel")
        self.xLabel = QtWidgets.QLabel(Form)
        self.xLabel.setGeometry(QtCore.QRect(5, 50, 60, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xLabel.sizePolicy().hasHeightForWidth())
        self.xLabel.setSizePolicy(sizePolicy)
        self.xLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.xLabel.setStyleSheet("font: 60pt \"Liberation Sans Narrow\";")
        self.xLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.xLabel.setObjectName("xLabel")
        self.xSecondaryDro = QtWidgets.QLabel(Form)
        self.xSecondaryDro.setGeometry(QtCore.QRect(476, 55, 131, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xSecondaryDro.sizePolicy().hasHeightForWidth())
        self.xSecondaryDro.setSizePolicy(sizePolicy)
        self.xSecondaryDro.setMinimumSize(QtCore.QSize(100, 0))
        self.xSecondaryDro.setStyleSheet("QLabel {\n"
"    border-style: solid;\n"
"    border-color: rgb(96, 96, 97);\n"
"    border-width: 1.5px;\n"
"    border-radius: 8px;\n"
"    color: white;\n"
"    background: rgb(86, 186, 187);\n"
"    font: 16pt \"Noto Sans Mono\";\n"
"}")
        self.xSecondaryDro.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xSecondaryDro.setObjectName("xSecondaryDro")
        self.zSecondaryDro = QtWidgets.QLabel(Form)
        self.zSecondaryDro.setGeometry(QtCore.QRect(476, 145, 131, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zSecondaryDro.sizePolicy().hasHeightForWidth())
        self.zSecondaryDro.setSizePolicy(sizePolicy)
        self.zSecondaryDro.setMinimumSize(QtCore.QSize(100, 0))
        self.zSecondaryDro.setStyleSheet("QLabel {\n"
"    border-style: solid;\n"
"    border-color: rgb(96, 96, 97);\n"
"    border-width: 1.5px;\n"
"    border-radius: 8px;\n"
"    color: white;\n"
"    background: rgb(86, 186, 187);\n"
"    font: 16pt \"Noto Sans Mono\";\n"
"}")
        self.zSecondaryDro.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zSecondaryDro.setObjectName("zSecondaryDro")
        self.xPrimaryDro = QtWidgets.QLabel(Form)
        self.xPrimaryDro.setGeometry(QtCore.QRect(610, 55, 316, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xPrimaryDro.sizePolicy().hasHeightForWidth())
        self.xPrimaryDro.setSizePolicy(sizePolicy)
        self.xPrimaryDro.setMinimumSize(QtCore.QSize(300, 0))
        self.xPrimaryDro.setStyleSheet("QLabel {\n"
"    font: 40pt \"Noto Sans Mono\";\n"
"    border-style: solid;\n"
"    border-color: rgb(10, 10, 10);\n"
"    border-width: 1.5px;\n"
"    border-radius: 8px;\n"
"    color: rgb(10, 10, 10);;\n"
"    background: rgb(217, 217, 217);\n"
"}")
        self.xPrimaryDro.setFrameShadow(QtWidgets.QFrame.Plain)
        self.xPrimaryDro.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xPrimaryDro.setObjectName("xPrimaryDro")
        self.zPrimaryDro = QtWidgets.QLabel(Form)
        self.zPrimaryDro.setGeometry(QtCore.QRect(610, 145, 316, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zPrimaryDro.sizePolicy().hasHeightForWidth())
        self.zPrimaryDro.setSizePolicy(sizePolicy)
        self.zPrimaryDro.setMinimumSize(QtCore.QSize(300, 0))
        self.zPrimaryDro.setStyleSheet("QLabel {\n"
"    font: 40pt \"Noto Sans Mono\";\n"
"    border-style: solid;\n"
"    border-color: rgb(10, 10, 10);\n"
"    border-width: 1.5px;\n"
"    border-radius: 8px;\n"
"    color: rgb(10, 10, 10);;\n"
"    background: rgb(217, 217, 217);\n"
"}")
        self.zPrimaryDro.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zPrimaryDro.setIndent(-1)
        self.zPrimaryDro.setObjectName("zPrimaryDro")
        self.zAbsRel = QtWidgets.QPushButton(Form)
        self.zAbsRel.setGeometry(QtCore.QRect(1230, 145, 71, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zAbsRel.sizePolicy().hasHeightForWidth())
        self.zAbsRel.setSizePolicy(sizePolicy)
        self.zAbsRel.setMinimumSize(QtCore.QSize(0, 0))
        self.zAbsRel.setStyleSheet("QPushButton {\n"
"    height: 60px;\n"
"    width: 60px;\n"
"    font: 14pt \"DejaVu Sans\";\n"
"}")
        self.zAbsRel.setObjectName("zAbsRel")
        self.xZero = QtWidgets.QPushButton(Form)
        self.xZero.setGeometry(QtCore.QRect(1135, 55, 71, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xZero.sizePolicy().hasHeightForWidth())
        self.xZero.setSizePolicy(sizePolicy)
        self.xZero.setMinimumSize(QtCore.QSize(40, 40))
        self.xZero.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.xZero.setStyleSheet("QPushButton {\n"
"    height: 60px;\n"
"    width: 60px;\n"
"    font: 14pt \"DejaVu Sans\";\n"
"}")
        self.xZero.setObjectName("xZero")
        self.xAbsRel = QtWidgets.QPushButton(Form)
        self.xAbsRel.setGeometry(QtCore.QRect(1230, 55, 71, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xAbsRel.sizePolicy().hasHeightForWidth())
        self.xAbsRel.setSizePolicy(sizePolicy)
        self.xAbsRel.setMinimumSize(QtCore.QSize(0, 0))
        self.xAbsRel.setStyleSheet("QPushButton {\n"
"    height: 60px;\n"
"    width: 60px;\n"
"    font: 14pt \"DejaVu Sans\";\n"
"}")
        self.xAbsRel.setObjectName("xAbsRel")
        self.zZero = QtWidgets.QPushButton(Form)
        self.zZero.setGeometry(QtCore.QRect(1135, 145, 71, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zZero.sizePolicy().hasHeightForWidth())
        self.zZero.setSizePolicy(sizePolicy)
        self.zZero.setMinimumSize(QtCore.QSize(0, 0))
        self.zZero.setStyleSheet("QPushButton {\n"
"    height: 60px;\n"
"    width: 60px;\n"
"    font: 14pt \"DejaVu Sans\";\n"
"}")
        self.zZero.setObjectName("zZero")
        self.zUnit = QtWidgets.QLabel(Form)
        self.zUnit.setGeometry(QtCore.QRect(930, 170, 31, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zUnit.sizePolicy().hasHeightForWidth())
        self.zUnit.setSizePolicy(sizePolicy)
        self.zUnit.setMinimumSize(QtCore.QSize(30, 0))
        self.zUnit.setStyleSheet("font: 18pt \"Liberation Mono\";")
        self.zUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.zUnit.setObjectName("zUnit")
        self.xUnit = QtWidgets.QLabel(Form)
        self.xUnit.setGeometry(QtCore.QRect(930, 80, 31, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xUnit.sizePolicy().hasHeightForWidth())
        self.xUnit.setSizePolicy(sizePolicy)
        self.xUnit.setMinimumSize(QtCore.QSize(30, 0))
        self.xUnit.setStyleSheet("font: 18pt \"Liberation Mono\";")
        self.xUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.xUnit.setObjectName("xUnit")
        self.mdibutton = MDIButton(Form)
        self.mdibutton.setGeometry(QtCore.QRect(1040, 145, 71, 71))
        self.mdibutton.setStyleSheet("")
        self.mdibutton.setObjectName("mdibutton")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(5, 220, 1300, 476))
        self.groupBox.setStyleSheet("")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.boxZMinusLimit = QtWidgets.QWidget(self.groupBox)
        self.boxZMinusLimit.setGeometry(QtCore.QRect(170, 275, 191, 56))
        self.boxZMinusLimit.setStyleSheet("QWidget #boxZMinusLimit{\n"
"    border-style: solid;\n"
"    border-color: rgb(10, 10, 10);\n"
"    border-width: 1px;\n"
"    border-radius: 8px;\n"
"    color: rgb(10, 10, 10);\n"
"}")
        self.boxZMinusLimit.setObjectName("boxZMinusLimit")
        self.teachZMinus = QtWidgets.QPushButton(self.boxZMinusLimit)
        self.teachZMinus.setGeometry(QtCore.QRect(115, 10, 66, 36))
        font = QtGui.QFont()
        font.setFamily("Cantarell Light")
        font.setPointSize(12)
        self.teachZMinus.setFont(font)
        self.teachZMinus.setStyleSheet("")
        self.teachZMinus.setObjectName("teachZMinus")
        self.droLabelZMinus = TeachInDroLabel(self.boxZMinusLimit)
        self.droLabelZMinus.setGeometry(QtCore.QRect(10, 10, 95, 36))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.droLabelZMinus.setFont(font)
        self.droLabelZMinus.setStyleSheet("QLabel {\n"
"        border-style: solid;\n"
"        border-color: rgb(119, 118, 123);\n"
"        border-width: 1px;\n"
"        border-radius: 5px;\n"
"        color: rgb(154, 153, 150);\n"
"        background: rgb(246, 245, 244);\n"
"        font: 12pt \"Noto Sans Mono\";\n"
"}")
        self.droLabelZMinus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.droLabelZMinus.setProperty("referenceType", 1)
        self.droLabelZMinus.setProperty("axisNumber", 2)
        self.droLabelZMinus.setProperty("latheMode", 0)
        self.droLabelZMinus.setObjectName("droLabelZMinus")
        self.boxZPlusLimit = QtWidgets.QWidget(self.groupBox)
        self.boxZPlusLimit.setGeometry(QtCore.QRect(900, 275, 191, 56))
        self.boxZPlusLimit.setStyleSheet("QWidget #boxZPlusLimit{\n"
"    border-style: solid;\n"
"    border-color: rgb(10, 10, 10);\n"
"    border-width: 1px;\n"
"    border-radius: 8px;\n"
"    color: rgb(10, 10, 10);\n"
"}")
        self.boxZPlusLimit.setObjectName("boxZPlusLimit")
        self.teachZPlus = QtWidgets.QPushButton(self.boxZPlusLimit)
        self.teachZPlus.setGeometry(QtCore.QRect(115, 10, 66, 36))
        font = QtGui.QFont()
        font.setFamily("Cantarell Light")
        font.setPointSize(12)
        self.teachZPlus.setFont(font)
        self.teachZPlus.setStyleSheet("")
        self.teachZPlus.setObjectName("teachZPlus")
        self.droLabelZPlus = TeachInDroLabel(self.boxZPlusLimit)
        self.droLabelZPlus.setGeometry(QtCore.QRect(10, 10, 95, 36))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.droLabelZPlus.setFont(font)
        self.droLabelZPlus.setStyleSheet("QLabel {\n"
"        border-style: solid;\n"
"        border-color: rgb(119, 118, 123);\n"
"        border-width: 1px;\n"
"        border-radius: 5px;\n"
"        color: rgb(154, 153, 150);\n"
"        background: rgb(246, 245, 244);\n"
"        font: 12pt \"Noto Sans Mono\";\n"
"}")
        self.droLabelZPlus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.droLabelZPlus.setProperty("referenceType", 1)
        self.droLabelZPlus.setProperty("axisNumber", 2)
        self.droLabelZPlus.setProperty("latheMode", 0)
        self.droLabelZPlus.setObjectName("droLabelZPlus")
        self.zLine = QtWidgets.QFrame(self.groupBox)
        self.zLine.setGeometry(QtCore.QRect(360, 295, 541, 20))
        self.zLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.zLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.zLine.setObjectName("zLine")
        self.tool_limits_label = QtWidgets.QLabel(self.groupBox)
        self.tool_limits_label.setGeometry(QtCore.QRect(560, 280, 171, 51))
        self.tool_limits_label.setStyleSheet("QLabel {\n"
"    font: 75 16pt \"Noto Mono\";\n"
"    border-style: solid;\n"
"    border-color: rgb(10, 10, 10);\n"
"    border-width: 1px;\n"
"    border-radius: 2px;\n"
"    color: rgb(10, 10, 10);;\n"
"    background: rgb(230, 230, 230);\n"
"}")
        self.tool_limits_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tool_limits_label.setObjectName("tool_limits_label")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(545, 45, 206, 51))
        self.label_6.setStyleSheet("QLabel {\n"
"    font: 75 16pt \"Noto Mono\";\n"
"    border-style: solid;\n"
"    border-color: rgb(10, 10, 10);\n"
"    border-width: 1px;\n"
"    border-radius: 2px;\n"
"    color: rgb(10, 10, 10);;\n"
"    background: rgb(230, 230, 230);\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.zLine_2 = QtWidgets.QFrame(self.groupBox)
        self.zLine_2.setGeometry(QtCore.QRect(140, 60, 961, 20))
        self.zLine_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.zLine_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.zLine_2.setObjectName("zLine_2")
        self.xLine = QtWidgets.QFrame(self.groupBox)
        self.xLine.setGeometry(QtCore.QRect(625, 205, 46, 206))
        self.xLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.xLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.xLine.setObjectName("xLine")
        self.boxXPlusLimit = QtWidgets.QWidget(self.groupBox)
        self.boxXPlusLimit.setGeometry(QtCore.QRect(555, 410, 191, 56))
        self.boxXPlusLimit.setStyleSheet("QWidget #boxXPlusLimit{\n"
"    border-style: solid;\n"
"    border-color: rgb(10, 10, 10);\n"
"    border-width: 1px;\n"
"    border-radius: 8px;\n"
"    color: rgb(10, 10, 10);\n"
"}")
        self.boxXPlusLimit.setObjectName("boxXPlusLimit")
        self.teachXPlus = QtWidgets.QPushButton(self.boxXPlusLimit)
        self.teachXPlus.setGeometry(QtCore.QRect(115, 10, 66, 36))
        font = QtGui.QFont()
        font.setFamily("Cantarell Light")
        font.setPointSize(12)
        self.teachXPlus.setFont(font)
        self.teachXPlus.setStyleSheet("")
        self.teachXPlus.setObjectName("teachXPlus")
        self.droLabelXPlus = TeachInDroLabel(self.boxXPlusLimit)
        self.droLabelXPlus.setGeometry(QtCore.QRect(10, 10, 95, 36))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.droLabelXPlus.setFont(font)
        self.droLabelXPlus.setStyleSheet("QLabel {\n"
"        border-style: solid;\n"
"        border-color: rgb(119, 118, 123);\n"
"        border-width: 1px;\n"
"        border-radius: 5px;\n"
"        color: rgb(154, 153, 150);\n"
"        background: rgb(246, 245, 244);\n"
"        font: 12pt \"Noto Sans Mono\";\n"
"}")
        self.droLabelXPlus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.droLabelXPlus.setProperty("referenceType", 1)
        self.droLabelXPlus.setProperty("axisNumber", 0)
        self.droLabelXPlus.setProperty("latheMode", 0)
        self.droLabelXPlus.setObjectName("droLabelXPlus")
        self.boxXMinusLimit = QtWidgets.QWidget(self.groupBox)
        self.boxXMinusLimit.setGeometry(QtCore.QRect(555, 150, 191, 56))
        self.boxXMinusLimit.setStyleSheet("QWidget #boxXMinusLimit{\n"
"    border-style: solid;\n"
"    border-color: rgb(10, 10, 10);\n"
"    border-width: 1px;\n"
"    border-radius: 8px;\n"
"    color: rgb(10, 10, 10);\n"
"}")
        self.boxXMinusLimit.setObjectName("boxXMinusLimit")
        self.teachXMinus = QtWidgets.QPushButton(self.boxXMinusLimit)
        self.teachXMinus.setGeometry(QtCore.QRect(115, 10, 66, 36))
        font = QtGui.QFont()
        font.setFamily("Cantarell Light")
        font.setPointSize(12)
        self.teachXMinus.setFont(font)
        self.teachXMinus.setStyleSheet("")
        self.teachXMinus.setObjectName("teachXMinus")
        self.droLabelXMinus = TeachInDroLabel(self.boxXMinusLimit)
        self.droLabelXMinus.setGeometry(QtCore.QRect(10, 10, 95, 36))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.droLabelXMinus.setFont(font)
        self.droLabelXMinus.setStyleSheet("QLabel {\n"
"        border-style: solid;\n"
"        border-color: rgb(119, 118, 123);\n"
"        border-width: 1px;\n"
"        border-radius: 5px;\n"
"        color: rgb(154, 153, 150);\n"
"        background: rgb(246, 245, 244);\n"
"        font: 12pt \"Noto Sans Mono\";\n"
"}")
        self.droLabelXMinus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.droLabelXMinus.setProperty("referenceType", 1)
        self.droLabelXMinus.setProperty("axisNumber", 0)
        self.droLabelXMinus.setProperty("latheMode", 0)
        self.droLabelXMinus.setObjectName("droLabelXMinus")
        self.boxTailstockLimit = QtWidgets.QWidget(self.groupBox)
        self.boxTailstockLimit.setGeometry(QtCore.QRect(1100, 45, 191, 56))
        self.boxTailstockLimit.setStyleSheet("QWidget #boxTailstockLimit{\n"
"    border-style: solid;\n"
"    border-color: rgb(10, 10, 10);\n"
"    border-width: 1px;\n"
"    border-radius: 8px;\n"
"    color: rgb(10, 10, 10);\n"
"}")
        self.boxTailstockLimit.setObjectName("boxTailstockLimit")
        self.teachTailstock = QtWidgets.QPushButton(self.boxTailstockLimit)
        self.teachTailstock.setGeometry(QtCore.QRect(115, 10, 66, 36))
        font = QtGui.QFont()
        font.setFamily("Cantarell Light")
        font.setPointSize(12)
        self.teachTailstock.setFont(font)
        self.teachTailstock.setStyleSheet("")
        self.teachTailstock.setObjectName("teachTailstock")
        self.droLabelTailstock = TeachInDroLabel(self.boxTailstockLimit)
        self.droLabelTailstock.setGeometry(QtCore.QRect(10, 10, 95, 36))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.droLabelTailstock.setFont(font)
        self.droLabelTailstock.setStyleSheet("QLabel {\n"
"        border-style: solid;\n"
"        border-color: rgb(119, 118, 123);\n"
"        border-width: 1px;\n"
"        border-radius: 5px;\n"
"        color: rgb(154, 153, 150);\n"
"        background: rgb(246, 245, 244);\n"
"        font: 12pt \"Noto Sans Mono\";\n"
"}")
        self.droLabelTailstock.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.droLabelTailstock.setProperty("referenceType", 0)
        self.droLabelTailstock.setProperty("axisNumber", 2)
        self.droLabelTailstock.setProperty("latheMode", 0)
        self.droLabelTailstock.setObjectName("droLabelTailstock")
        self.labelXPlusLimit = QtWidgets.QLabel(self.groupBox)
        self.labelXPlusLimit.setGeometry(QtCore.QRect(460, 430, 90, 19))
        self.labelXPlusLimit.setStyleSheet("QLabel {\n"
"    font: 75 14pt \"Noto Mono\";\n"
"}")
        self.labelXPlusLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.labelXPlusLimit.setObjectName("labelXPlusLimit")
        self.zMinusToggle = QtWidgets.QPushButton(self.groupBox)
        self.zMinusToggle.setEnabled(False)
        self.zMinusToggle.setGeometry(QtCore.QRect(205, 340, 120, 45))
        font = QtGui.QFont()
        font.setFamily("Cantarell Light")
        font.setPointSize(12)
        self.zMinusToggle.setFont(font)
        self.zMinusToggle.setStyleSheet("")
        self.zMinusToggle.setCheckable(True)
        self.zMinusToggle.setObjectName("zMinusToggle")
        self.labelZMinusLimit = QtWidgets.QLabel(self.groupBox)
        self.labelZMinusLimit.setGeometry(QtCore.QRect(210, 250, 111, 19))
        self.labelZMinusLimit.setStyleSheet("QLabel {\n"
"    font: 75 14pt \"Noto Mono\";\n"
"}")
        self.labelZMinusLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.labelZMinusLimit.setObjectName("labelZMinusLimit")
        self.zPlusToggle = QtWidgets.QPushButton(self.groupBox)
        self.zPlusToggle.setEnabled(False)
        self.zPlusToggle.setGeometry(QtCore.QRect(935, 340, 120, 45))
        font = QtGui.QFont()
        font.setFamily("Cantarell Light")
        font.setPointSize(12)
        self.zPlusToggle.setFont(font)
        self.zPlusToggle.setStyleSheet("")
        self.zPlusToggle.setCheckable(True)
        self.zPlusToggle.setObjectName("zPlusToggle")
        self.labelZPlusLimit = QtWidgets.QLabel(self.groupBox)
        self.labelZPlusLimit.setGeometry(QtCore.QRect(945, 250, 111, 19))
        self.labelZPlusLimit.setStyleSheet("QLabel {\n"
"    font: 75 14pt \"Noto Mono\";\n"
"}")
        self.labelZPlusLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.labelZPlusLimit.setObjectName("labelZPlusLimit")
        self.tailstockToggle = QtWidgets.QPushButton(self.groupBox)
        self.tailstockToggle.setEnabled(False)
        self.tailstockToggle.setGeometry(QtCore.QRect(1135, 110, 120, 45))
        font = QtGui.QFont()
        font.setFamily("Cantarell Light")
        font.setPointSize(12)
        self.tailstockToggle.setFont(font)
        self.tailstockToggle.setStyleSheet("")
        self.tailstockToggle.setCheckable(True)
        self.tailstockToggle.setChecked(False)
        self.tailstockToggle.setDefault(False)
        self.tailstockToggle.setObjectName("tailstockToggle")
        self.labelTailstockLimit = QtWidgets.QLabel(self.groupBox)
        self.labelTailstockLimit.setGeometry(QtCore.QRect(1100, 20, 186, 19))
        self.labelTailstockLimit.setStyleSheet("QLabel {\n"
"    font: 75 14pt \"Noto Mono\";\n"
"}")
        self.labelTailstockLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTailstockLimit.setObjectName("labelTailstockLimit")
        self.xPlusToggle = QtWidgets.QPushButton(self.groupBox)
        self.xPlusToggle.setEnabled(False)
        self.xPlusToggle.setGeometry(QtCore.QRect(755, 415, 120, 45))
        font = QtGui.QFont()
        font.setFamily("Cantarell Light")
        font.setPointSize(12)
        self.xPlusToggle.setFont(font)
        self.xPlusToggle.setStyleSheet("")
        self.xPlusToggle.setCheckable(True)
        self.xPlusToggle.setObjectName("xPlusToggle")
        self.labelXMinusLimit = QtWidgets.QLabel(self.groupBox)
        self.labelXMinusLimit.setGeometry(QtCore.QRect(460, 170, 90, 19))
        self.labelXMinusLimit.setStyleSheet("QLabel {\n"
"    font: 75 14pt \"Noto Mono\";\n"
"}")
        self.labelXMinusLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.labelXMinusLimit.setObjectName("labelXMinusLimit")
        self.xMinusToggle = QtWidgets.QPushButton(self.groupBox)
        self.xMinusToggle.setEnabled(False)
        self.xMinusToggle.setGeometry(QtCore.QRect(755, 155, 120, 45))
        font = QtGui.QFont()
        font.setFamily("Cantarell Light")
        font.setPointSize(12)
        self.xMinusToggle.setFont(font)
        self.xMinusToggle.setStyleSheet("")
        self.xMinusToggle.setCheckable(True)
        self.xMinusToggle.setObjectName("xMinusToggle")
        self.labelChuckLimit = QtWidgets.QLabel(self.groupBox)
        self.labelChuckLimit.setGeometry(QtCore.QRect(15, 20, 131, 19))
        self.labelChuckLimit.setStyleSheet("QLabel {\n"
"    font: 75 14pt \"Noto Mono\";\n"
"}")
        self.labelChuckLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.labelChuckLimit.setObjectName("labelChuckLimit")
        self.boxChuckLimit = QtWidgets.QWidget(self.groupBox)
        self.boxChuckLimit.setGeometry(QtCore.QRect(15, 45, 126, 56))
        self.boxChuckLimit.setStyleSheet("QWidget #boxChuckLimit{\n"
"    border-style: solid;\n"
"    border-color: rgb(10, 10, 10);\n"
"    border-width: 1px;\n"
"    border-radius: 8px;\n"
"    color: rgb(10, 10, 10);\n"
"}")
        self.boxChuckLimit.setObjectName("boxChuckLimit")
        self.droChuckLimit = TeachInDroLabel(self.boxChuckLimit)
        self.droChuckLimit.setGeometry(QtCore.QRect(10, 10, 106, 36))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.droChuckLimit.setFont(font)
        self.droChuckLimit.setStyleSheet("QLabel {\n"
"        border-style: solid;\n"
"        border-color: rgb(119, 118, 123);\n"
"        border-width: 1px;\n"
"        border-radius: 5px;\n"
"        color: rgb(154, 153, 150);\n"
"        background: rgb(246, 245, 244);\n"
"        font: 12pt \"Noto Sans Mono\";\n"
"}")
        self.droChuckLimit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.droChuckLimit.setProperty("referenceType", 1)
        self.droChuckLimit.setProperty("axisNumber", 0)
        self.droChuckLimit.setProperty("latheMode", 0)
        self.droChuckLimit.setObjectName("droChuckLimit")
        self.changeChuck = QtWidgets.QPushButton(self.groupBox)
        self.changeChuck.setGeometry(QtCore.QRect(20, 110, 120, 45))
        font = QtGui.QFont()
        font.setFamily("Cantarell Light")
        font.setPointSize(12)
        self.changeChuck.setFont(font)
        self.changeChuck.setStyleSheet("")
        self.changeChuck.setObjectName("changeChuck")
        self.boxChuckLimit.raise_()
        self.boxZMinusLimit.raise_()
        self.boxZPlusLimit.raise_()
        self.zLine.raise_()
        self.zLine_2.raise_()
        self.xLine.raise_()
        self.tool_limits_label.raise_()
        self.boxXPlusLimit.raise_()
        self.boxXMinusLimit.raise_()
        self.boxTailstockLimit.raise_()
        self.labelXPlusLimit.raise_()
        self.zMinusToggle.raise_()
        self.labelZMinusLimit.raise_()
        self.zPlusToggle.raise_()
        self.labelZPlusLimit.raise_()
        self.tailstockToggle.raise_()
        self.labelTailstockLimit.raise_()
        self.xPlusToggle.raise_()
        self.labelXMinusLimit.raise_()
        self.xMinusToggle.raise_()
        self.labelChuckLimit.raise_()
        self.changeChuck.raise_()
        self.label_6.raise_()
        self.drolabel = DROLabel(Form)
        self.drolabel.setGeometry(QtCore.QRect(85, 55, 311, 71))
        self.drolabel.setStyleSheet("QLabel {\n"
"    font: 40pt \"Noto Sans Mono\";\n"
"    border-style: solid;\n"
"    border-color: rgb(200, 200, 200);\n"
"    border-width: 1.5px;\n"
"    border-radius: 8px;\n"
"    color: rgb(150, 150, 150);;\n"
"    background: rgb(230, 230, 230);\n"
"}")
        self.drolabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drolabel.setProperty("referenceType", 0)
        self.drolabel.setProperty("axisNumber", 0)
        self.drolabel.setProperty("latheMode", 1)
        self.drolabel.setObjectName("drolabel")
        self.drolabel_2 = DROLabel(Form)
        self.drolabel_2.setGeometry(QtCore.QRect(85, 145, 311, 71))
        self.drolabel_2.setStyleSheet("QLabel {\n"
"    font: 40pt \"Noto Sans Mono\";\n"
"    border-style: solid;\n"
"    border-color: rgb(200, 200, 200);\n"
"    border-width: 1.5px;\n"
"    border-radius: 8px;\n"
"    color: rgb(150, 150, 150);;\n"
"    background: rgb(230, 230, 230);\n"
"}")
        self.drolabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drolabel_2.setProperty("referenceType", 0)
        self.drolabel_2.setProperty("axisNumber", 2)
        self.drolabel_2.setProperty("latheMode", 0)
        self.drolabel_2.setObjectName("drolabel_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(85, 10, 311, 31))
        self.label_4.setStyleSheet("font: 18pt \"Cantarell\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(610, 10, 311, 31))
        self.label_8.setStyleSheet("font: 18pt \"Cantarell\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(5, 10, 66, 31))
        self.label_9.setStyleSheet("font: 18pt \"Cantarell\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(1045, 5, 246, 31))
        self.label_10.setStyleSheet("font: 18pt \"Cantarell\";")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.groupBox.raise_()
        self.zLabel.raise_()
        self.xLabel.raise_()
        self.xSecondaryDro.raise_()
        self.zSecondaryDro.raise_()
        self.xPrimaryDro.raise_()
        self.zPrimaryDro.raise_()
        self.zAbsRel.raise_()
        self.xZero.raise_()
        self.xAbsRel.raise_()
        self.zZero.raise_()
        self.zUnit.raise_()
        self.xUnit.raise_()
        self.mdibutton.raise_()
        self.drolabel.raise_()
        self.drolabel_2.raise_()
        self.label_4.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()

        self.retranslateUi(Form)
        self.teachZMinus.clicked.connect(self.droLabelZMinus.fillWithCurrentValue) # type: ignore
        self.teachZPlus.clicked.connect(self.droLabelZPlus.fillWithCurrentValue) # type: ignore
        self.teachTailstock.clicked.connect(self.droLabelTailstock.fillWithCurrentValue) # type: ignore
        self.teachXMinus.clicked.connect(self.droLabelXMinus.fillWithCurrentValue) # type: ignore
        self.teachXPlus.clicked.connect(self.droLabelXPlus.fillWithCurrentValue) # type: ignore
        self.zMinusToggle.toggled['bool'].connect(self.teachZMinus.setDisabled) # type: ignore
        self.zPlusToggle.toggled['bool'].connect(self.teachZPlus.setDisabled) # type: ignore
        self.xPlusToggle.toggled['bool'].connect(self.teachXPlus.setDisabled) # type: ignore
        self.xMinusToggle.toggled['bool'].connect(self.teachXMinus.setDisabled) # type: ignore
        self.tailstockToggle.toggled['bool'].connect(self.teachTailstock.setDisabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.zLabel.setText(_translate("Form", "Z"))
        self.xLabel.setText(_translate("Form", "X"))
        self.xSecondaryDro.setText(_translate("Form", "+0000.000"))
        self.zSecondaryDro.setText(_translate("Form", "+0000.000"))
        self.xPrimaryDro.setText(_translate("Form", "+0000.000"))
        self.zPrimaryDro.setText(_translate("Form", "+0000.000"))
        self.zAbsRel.setText(_translate("Form", "A/R"))
        self.xZero.setText(_translate("Form", "0"))
        self.xAbsRel.setText(_translate("Form", "A/R"))
        self.zZero.setText(_translate("Form", "0"))
        self.zUnit.setText(_translate("Form", "mm"))
        self.xUnit.setText(_translate("Form", "mm"))
        self.mdibutton.setText(_translate("Form", "Set\n"
"Datum"))
        self.mdibutton.setProperty("rules", _translate("Form", "[{\"name\": \"enable set datum\", \"property\": \"Enable\", \"expression\": \"ch[0] != 0\", \"channels\": [{\"url\": \"status:tool_in_spindle\", \"trigger\": true}]}]"))
        self.mdibutton.setProperty("MDICommand", _translate("Form", "G10 L20 P0 Z0"))
        self.teachZMinus.setText(_translate("Form", "TeachIn"))
        self.droLabelZMinus.setText(_translate("Form", "1000.234"))
        self.droLabelZMinus.setProperty("inchFormat", _translate("Form", "%9.4f"))
        self.droLabelZMinus.setProperty("millimeterFormat", _translate("Form", "%10.3f"))
        self.droLabelZMinus.setProperty("degreeFormat", _translate("Form", "%10.2f"))
        self.teachZPlus.setText(_translate("Form", "TeachIn"))
        self.droLabelZPlus.setText(_translate("Form", "1000.234"))
        self.droLabelZPlus.setProperty("inchFormat", _translate("Form", "%9.4f"))
        self.droLabelZPlus.setProperty("millimeterFormat", _translate("Form", "%10.3f"))
        self.droLabelZPlus.setProperty("degreeFormat", _translate("Form", "%10.2f"))
        self.tool_limits_label.setText(_translate("Form", "Tool Limits"))
        self.label_6.setText(_translate("Form", "Machine Limits"))
        self.teachXPlus.setText(_translate("Form", "TeachIn"))
        self.droLabelXPlus.setText(_translate("Form", "1000.234"))
        self.droLabelXPlus.setProperty("inchFormat", _translate("Form", "%9.4f"))
        self.droLabelXPlus.setProperty("millimeterFormat", _translate("Form", "%10.3f"))
        self.droLabelXPlus.setProperty("degreeFormat", _translate("Form", "%10.2f"))
        self.teachXMinus.setText(_translate("Form", "TeachIn"))
        self.droLabelXMinus.setText(_translate("Form", "1000.234"))
        self.droLabelXMinus.setProperty("inchFormat", _translate("Form", "%9.4f"))
        self.droLabelXMinus.setProperty("millimeterFormat", _translate("Form", "%10.3f"))
        self.droLabelXMinus.setProperty("degreeFormat", _translate("Form", "%10.2f"))
        self.teachTailstock.setText(_translate("Form", "TeachIn"))
        self.droLabelTailstock.setText(_translate("Form", "1000.234"))
        self.droLabelTailstock.setProperty("inchFormat", _translate("Form", "%9.4f"))
        self.droLabelTailstock.setProperty("millimeterFormat", _translate("Form", "%10.3f"))
        self.droLabelTailstock.setProperty("degreeFormat", _translate("Form", "%10.2f"))
        self.labelXPlusLimit.setText(_translate("Form", "Limit X+"))
        self.zMinusToggle.setText(_translate("Form", "Enable Limit"))
        self.labelZMinusLimit.setText(_translate("Form", "Limit Z-"))
        self.zPlusToggle.setText(_translate("Form", "Enable Limit"))
        self.labelZPlusLimit.setText(_translate("Form", "Limit Z+"))
        self.tailstockToggle.setText(_translate("Form", "Enable Limit"))
        self.labelTailstockLimit.setText(_translate("Form", "Tailstock Limit"))
        self.xPlusToggle.setText(_translate("Form", "Enable Limit"))
        self.labelXMinusLimit.setText(_translate("Form", "Limit X-"))
        self.xMinusToggle.setText(_translate("Form", "Enable Limit"))
        self.labelChuckLimit.setText(_translate("Form", "Chuck Limit"))
        self.droChuckLimit.setText(_translate("Form", "1000.234"))
        self.droChuckLimit.setProperty("inchFormat", _translate("Form", "%9.4f"))
        self.droChuckLimit.setProperty("millimeterFormat", _translate("Form", "%10.3f"))
        self.droChuckLimit.setProperty("degreeFormat", _translate("Form", "%10.2f"))
        self.changeChuck.setText(_translate("Form", "Change Chuck"))
        self.drolabel.setText(_translate("Form", "     0.000"))
        self.drolabel.setProperty("inchFormat", _translate("Form", "%9.4f"))
        self.drolabel.setProperty("millimeterFormat", _translate("Form", "%10.3f"))
        self.drolabel.setProperty("degreeFormat", _translate("Form", "%10.2f"))
        self.drolabel_2.setText(_translate("Form", "     0.000"))
        self.drolabel_2.setProperty("inchFormat", _translate("Form", "%9.4f"))
        self.drolabel_2.setProperty("millimeterFormat", _translate("Form", "%10.3f"))
        self.drolabel_2.setProperty("degreeFormat", _translate("Form", "%10.2f"))
        self.label_4.setText(_translate("Form", "Machine Coordinates"))
        self.label_8.setText(_translate("Form", "Tool Coordinates #1"))
        self.label_9.setText(_translate("Form", "Axis"))
        self.label_10.setText(_translate("Form", "Actions"))
from qtpyvcp.widgets.button_widgets.mdi_button import MDIButton
from qtpyvcp.widgets.display_widgets.dro_label import DROLabel
from qtpyvcp.widgets.input_widgets.teachin_dro_label import TeachInDroLabel
